spring.application.name=lms-platform

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:lmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create tables automatically
spring.jpa.hibernate.ddl-auto=update

# Disable Docker Compose (we use H2 for now)
spring.docker.compose.enabled=false

# Enable H2 Console (optional, to see DB in browser at /h2-console)
spring.h2.console.enabled=true
