spring.application.name=lms-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=v3ry-StR0ng-P@ssw0rd-2026
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop
